FROM python:3.4

ENV PYTHONUNBUFFERED 1

COPY . /app
RUN pip install -r /app/requirements.txt

COPY ./entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
